### ISSUE TITLE
Document Skycoin Ledger Nano app architecture

### ISSUE THREAD

**Issue by olemis** [skycoin/ledger-nano#1]
- [x] Initial research(BOLOS overview and architecture) 
- [x] Sources compilation
- [ ] How the communication between the bolos app and companion app flow (APDU requests)
- [ ] User interface and small "how to use" tutorial 
- [ ] Roadmap

**Comment by jdknives** [comment]
All of those points (except the Roadmap) are implicitly being done, right now? So this could be closed?

**Comment by Midren** [comment]
There is no how to use, but it is useless, while we don't complete app and we also need to specify exact format for an APDU call for signing transaction.
