### ISSUE TITLE
Move from BIP32 to BIP44

### ISSUE THREAD

**Issue by Retsediv** [skycoin/ledger-nano#16]
**Feature description**
Currently, we are using BIP32 for path derivation and want to move to BIP44.
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

After that, we will be able to register skycoin [here](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

**Describe the solution you'd like**
In order to do this we to implement the following:

- [x]   Change the current code (mostly(or even entirely) in `main.c` get public key APDU call)
- [x]   Fix python scripts, which test APDU request to use there BIP44 instead of BIP32

**Comment by jdknives** [comment]
Closed by #14
