### ISSUE TITLE
Initial source code

### ISSUE THREAD

**Issue by olemis** [skycoin/ledger-nano#2]
**Feature description**

Initialize source code version control repository.

**Describe the solution you'd like**
Initial (unfinished) code with tests.

**Describe alternatives you've considered**
Appveyor for Windows CI builds

**Possible implementation**

- [x] Initial code
- [x] Make targets
- [x] Concise README
- [x] Empty CHANGELOG
- [x] Travis build matrix for linux and osx
- [x] Setup BOLOS dev env
- [x] Compile source code
- [x] Check communication between ledget and desktop

**Comment by Retsediv** [comment]
Finished
