### ISSUE TITLE
Add menu with app version and small description

### ISSUE THREAD

**Issue by Retsediv** [skycoin/ledger-nano#9]
**Feature description**
Simple menu for the app, where user can check app version, description. 

**Example of how it could looks like**
![8f7e79b8-2e4a-4517-b134-4c71f163d356](https://user-images.githubusercontent.com/10120566/52576062-1527a500-2e28-11e9-92da-c58b5a18dd1d.jpeg)
![8cbd84b4-0072-4052-ae58-09d74c071988](https://user-images.githubusercontent.com/10120566/52576126-35576400-2e28-11e9-96d7-c2df52b92546.jpeg)
![1c88d9a6-81f1-4ad6-b283-51fdc06b6a00](https://user-images.githubusercontent.com/10120566/52576142-39838180-2e28-11e9-95ce-f25b26cc8565.jpeg)

**Additional usage**
Later we can paste there the link to the documentation page, where the basic workflow will be described(e.g. https://hycon.io/en/ledger/)

Part of #3

**Comment by jdknives** [comment]
Closed by #14
